name: Build & Push Docker image to Docker Hub

on:
  push:
    branches: [ main ]  # or 'dev' or any branch you want

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image with tags
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/socialaggregatorapi:dev ./SocialAggregatorAPI
        docker tag tsts83/socialaggregatorapi:latest
        docker push tsts83/socialaggregatorapi:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/socialaggregatorapi:latest
